// Supabase config
window.SUPABASE_URL = "https://oiozdxqxfujxkknngsxp.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pb3pkeHF4ZnVqeGtrbm5nc3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NDcyNDIsImV4cCI6MjA5MjMyMzI0Mn0.cp6q8bG0nEkVMPwz8wU-fTppTn4-NxPWeonURnbVyWA";

// PayPal config
window.PAYPAL_CLIENT_ID = "AfLMHq4YC9sgv4TPGhO-qwM8pQyoZ-Zo5j5Zw1TRmMhUKg75RR0WBxUIhySdRDoIorfUv2kkxyzT32lO";